server:
  port: 2000
  
spring:
  data:
    cassandra:
      port: 9042
      keyspace-name: main
      local-datacenter: ${CASSANDRA_DC}
      schema-action: create-if-not-exists
      contact-points:
      - ${CASSANDRA_SEEDS}
#      - host.docker.internal