apiVersion: v1
kind: Service
metadata:
  name: spring-data-cassandra-service
spec:
  selector:
    app: spring-data-cassandra-service
  ports:
    - protocol: TCP
      port: 2000
      nodePort: 31081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-data-cassandra-service
  labels:
    app: spring-data-cassandra-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-data-cassandra-service
  template:
    metadata:
      labels:
        app: spring-data-cassandra-service
    spec:
      containers:
      - name: spring-data-cassandra-service
        image: khushi1701/spring-data-cassandra
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2000