spring:
  data:
    cassandra:
      port: 9042
      keyspace-name: local_keyspace 
      schema-action: create-if-not-exists
      local-datacenter: datacenter1
      contact-points:
      - 127.0.0.1, localhost