#spring:
#  data:
#    cassandra:
#      port: 9041
#      keyspace-name: docker_keyspace
#      schema-action: CREATE_IF_NOT_EXISTS
#      local-datacenter: datacenter1
#      contact-points: host.docker.internal